name: py37
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.8.1=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h7a1dbc1_0
  - cudatoolkit=10.1.243=h74a9793_0
  - cycler=0.10.0=py37_0
  - entrypoints=0.3=py37_0
  - flake8=3.7.9=py37_0
  - freetype=2.9.1=ha9979f8_1
  - grpcio=1.16.1=py37h351948d_1
  - h5py=2.8.0=py37hf7173ca_2
  - hdf5=1.8.20=hac2f561_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - intel-openmp=2019.4=245
  - joblib=0.14.1=py_0
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.1.0=py37ha925a31_0
  - libopencv=3.4.2=h20b85fd_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.10.1=h7bd577a_0
  - libtiff=4.1.0=h56a325e_0
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.1=py37hc8f65d3_0
  - mccabe=0.6.1=py37_1
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - ninja=1.9.0=py37h74a9793_0
  - numpy=1.17.3=py37h4ceb530_0
  - numpy-base=1.17.3=py37hc3f5095_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h40b0b35_0
  - openssl=1.1.1d=he774522_4
  - pandas=0.25.3=py37ha925a31_0
  - pillow=6.2.1=py37hdc69c19_0
  - pip=19.3.1=py37_0
  - prettytable=0.7.2=py_3
  - protobuf=3.10.1=py37h33f27b4_0
  - psutil=5.6.7=py37he774522_0
  - py-opencv=3.4.2=py37hc319ecb_0
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.19=py37_0
  - pyflakes=2.1.1=py37_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyreadline=2.1=py37_1
  - python=3.7.5=h8c8aaf0_0
  - python-dateutil=2.8.1=py_0
  - pytorch=1.3.1=py3.7_cuda101_cudnn7_0
  - pytz=2019.3=py_0
  - qt=5.9.7=vc14h73c81de_0
  - scikit-learn=0.22.1=py37h6288b17_0
  - scipy=1.4.1=py37h9439919_0
  - setuptools=42.0.1=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=he774522_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tk=8.6.8=hfa6e2cd_0
  - tornado=6.0.3=py37he774522_0
  - tqdm=4.39.0=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - wincertstore=0.2=py37_0
  - xz=5.2.4=h2fa13f4_4
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
prefix: C:\ProgramData\Anaconda3\envs\py37

